version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"

  redis:
    image: "redis:alpine"

  resume:
    image: nginx:latest
    ports: "8080:80"
    volumes:
    - "/home/scarrasco/Git/resume/dist:/usr/share/nginx/html:ro"

  dashbaord:
    image: nginx:latest
    ports: "8081:80"
    volumes:
    - "/home/scarrasco/Git/dashbaord/dist:/usr/share/nginx/html:ro"
    
  blog:
    image: nginx:latest
    ports: "8082:80"
    volumes:
    - "/home/scarrasco/Git/blog/dist:/usr/share/nginx/html:ro" 

  coffee:
    image: nginx:latest
    ports: "8083:80"
    volumes:
    - "/home/scarrasco/Git/coffee/dist:/usr/share/nginx/html:ro"  